---
title: "07 - ggplot2"
author: "Ccanadas"
date: "2022-09-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 library(ggplot2)
 
 1º) DATOS
 2º) GEOM: geometrías (tipo de gráfico)
 3º) Estéticas: aes (color, tamaño, forma, posición,...)
 4º) Factor de escala: scale (información más allá de los datos)
 
 Ir añadiendo a partir de + las personalizaciones
 
# Gráficos de dispersión

inicializar gráfico:
plot<-ggplot(df, aes(x,y))

añadir capas: 
plot+geom_point()
plot+geom_point(alpha=.5, size=5, aes(color=factor(factor_col))) ##Añadir colores por factor +
     geom_smooth(method="lm", se=FALSE, col="green") +
     
     ##se=TRUE pinta el intervalo de confianza
     
más opciones de representación:
facet_grid(y(factor)~.) ##Representar gráficos separados por factor (podemos hacer .~y para trasponer)
theme_bw(base_family="Arial", base_size=10)  ##tema (familia de fuentes)
labs(x="xlab")+labs(y="ylab)  ##etiquetas
labs(title="titulo")

     ##facet_wrap: añadir más dimensiones al gráfico: envolver los gráficos en filas y columnas coherentes
 
qplot<-versión simplificada de ggplot2

ej: qplot(x=x, y =y , data = df,
      geom=c("point", "smooth"), method = "lm", 
      formula = y~x, color = factor, 
      main = "titulo")


#Gráficos de líneas
 
plot<-ggplot(df, aes(x,y))
plot+geom_line()
plot+geom_line(linetype="dashed")
plot+geom_line(color="color")

parámetros: tamaño, tipo , etc.. (podemos utilizar los parámetros dentro del mismo geom_line)

plot+geom_line(aes(color=as.factor(columna)))  agrupar lineas por color/categoría




# Gráfico de barras
 
library(dplyr) ##instrucciones bases de datos 

1º) crear un df que resuma la información (variables de conteo)
 
 df.sum=df%>%
 group_by(factor1, factor2)%>%
 summarize(variable_de_conteo=sum(cnt))
 
 df.sum
 
 2º) plot
 
 ggplot(df.sum, aes(x=x, y=y, fill=otra_variable, label=scales::comma(variable_conteo)))+ ##fill, separa por colores otro factor
 geom_bar(show.legend=T, stat="identity, fill="color", colour="black")+ ##stat identity muestra que la Y es una col del dataset/stat=bin si no lo es
 labs(title="titulo")+
 scale_y_continuous(labels=scales::comma)+ ##etiquetas dentro de las cajas
 geom_text(size=3, position=position_stack(vjust=0.5)) ##formato etiquetas
 
 
 
# Gráficos de distribuciones
 
plot<-ggplot(df, aes(x=x_var)) 
plot+geom_histogram() + ##frec. absolutas
plot+geom_histogram(binwidth=5, fill="color", colour="black") + ##número de divisiones/anchura division

Para representar la función de densidad:

1º) cambiar a frec. relativas

ggplot(df, aes=(x=x, y=..density..))+
geom_histogram(fill="cornsilk", color="grey6", size=.2)+

2º) añadir la función de densidad

geom_density()+xlim(n,m) ##para ajustar la línea de densidad y suavizar los límites



# Gráficos de mosáicos

Concurrencia de probabilidades condicionales

library(stats)

mosaicplot(~var1+var2, data=df, color=n:m o color=T, las=1)

solo hay que aplicar las variables que vamos a cruzar y las columnar en el vector de color


# Treemaps

library(treemap)

1º) construir un df ramificado: variables categóricas y un valor

branch <- c(rep("branch-1",4), rep("branch-2",2), rep("branch-3",3))
subbranch <- paste("subbranch",c(1,2,3,4,1,2,1,2,3), sep = "-")
values = c(15,4,22,13,11,8,6,1,25)
data <- data.frame(branch, subbranch, values)

treemap(data, index = c("branch", "subbranch"),
        vSize = "values", type = "index")


2º) a partir de un df

treemap(df, 
        index = c("var_1", "var_2"),
        vSize = "var_value", type = "index")


# Gráficos con matrices de correlación

library(corrplot)

Calcular coeficientes de correlación con métodos: Pearson, Spearman, etc...

df.cor<-cor(df, method="pearson")

corrplot(df.cor) ##círculos

corrplot(df.cor, method=shade, shade.col=NA, tl.col="black", tl.srt=45) ##cuadrados //tl=etiquetas

method=color, shade, square, circle, elipse, pie

Podemos crear paletas de colores y ordenar

col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", 
                          "#77AADD", "#4477AA")) ##pillar paletas de internet

corrplot(df, method = "square", 
         tl.col = "black",
         tl.srt = 45, col = col(200), ##(200) es la expansión de colores
         shade.col=NA ##quita las lineas de correlación diagonales
         addCoef.col = "black", ## añadir coeficientes
         order = "AOE",  ## ordenar según el valor/clust para ordenader
         type = "upper", ## solo el triángulo superior (por simetria)
         diag = F, ## quitar la diagonal =1
         addshade = "all") ## añadir las lineas diagonales de correlacion
         

## Matrices de correlación con ggplot2 y mapas de calor

library(reshape2)
df <- melt(df.cor)


ggplot(data = df.melted, 
       aes(x=Var1, y=Var2,fill=value))+
  geom_tile()

### Crear mapa de calor: funciones útiles

Entrada: matriz de correlaciones

get_lower_triangle <- function(cormat){
  cormat[upper.tri(cormat)] <- NA
  return(cormat)
}

get_upper_triangle <- function(cormat){
  cormat[lower.tri(cormat)] <- NA
  return(cormat)
}

reorder_cormat <- function(cormat){
  dd <- as.dist((1-cormat)/2)
  hc <- hclust(dd)
  cormat <- cormat[hc$order, hc$order]
 
 
 Crear matriz de correlación ordenada, nos quedamos con el triángul superior y lo fundimos
 
 cormat<-reorder_cormat(df.cor)
 cormat.ut<-get_upper_triangle(cormat)
 cormat.ut.melted<-melt(cormat.ut, na.rm=T)
 
 ggplot(cormat.ut.melted, aes(Var2, Var1, fill = value)) + 
  geom_tile(color = "white")+
  scale_fill_gradient2(low = "blue", high = "red", ##gradiente de color
                       mid = "white", midpoint = 0,
                       limit = c(-1,1), space = "Lab",
                       name="Pearson\nCorrelation")+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, vjust=1, 
                                   size = 12, hjust=1))+
  coord_fixed()

 
# Graphs - Red de grafos

library(igraph)

se escriben los elementos(aristas) dos a dos:

g.dir <- graph(edges = c(1,2, 2,3, 2,4, 1,4, 5,5, 3,6, 5,6), n=6) ##vectores origen,destino, n=nodos
g.n_dir <- graph(edges = c(1,2, 2,3, 2,4, 1,4,
                           5,5, 3,6, 5,6), n=6, directed = F) #no dirigido

plot(g.dir)
plot(g.n_dir)

con elementos aislados:

g_isolated <- graph(edges = c("Juan", "María", 
                      "María", "Ana",
                      "Ana", "Juan", 
                      "José", "María",
                      "Pedro", "José",
                      "Joel", "Pedro"),
                    isolates = c( "Carmen", "Antonio",  ##no relacionados
                                  "Mario", "Vicente"))

personalizado:


par(mfrow = c(1,1))
plot(g_isolated, edge.arrow.size = 1,
     vertex.color="gold",vertex.size = 15,
     vertex.frame.color = "gray", 
     vertex.label.color = "black",
     vertex.label.cex = 0.8,
     vertex.label.dist = 2,
     edge.curved=0.2)


 Si queremos que siempre salga igual set_seed() configuramos una semilla.
 
 
# Etiquetas y leyendas
 
ggtitle(titulo)
xlab(eje x)
ylab(eje y)
labs(....)

...boxplot(x,y,fill)...+

labs(fill = "factor") + ## split por factor - etiquetas en la leyenda
theme(legend.position = "bottom") + ##posición leyenda
guides(fill = F) ## nos cargamos la leyenda

### Temas

theme_bw()+
theme_dark()+
theme_classic()+
theme_grey()+
theme(plot.background = element_rect(fill="darkblue"))
theme(axis.text.x = element_text(face = "bold", 
                                   family = "Times",
                                   size = 14,
                                   angle = 45,
                                   color = "#995566"),
        axis.text.y = element_text(face = "italic",
                                   family = "Courier",
                                   size = 16,
                                   angle = 30, 
                                   color = "#449955")
        )+
theme(panel.border = element_blank())+ ##eliminar borde del gráfico
theme(panel.grid.major = element_blank(), ##eliminar la parrilla mayor (grid)
panel.grid.minor = element_blank()) ##eliminar la parrilla menor


# Gráficos multivariante

library(ggplot2)
library(GGally)

ggplot(df, aes(x=x, y = y))+
  geom_point(size=3, aes(color=variable_factor))+
  theme(legend.position = "bottom")+
  geom_smooth(method="lm", se=F, col="red")+
  facet_grid(var_y1 ~ var_x2) ##añadir dimensión adicional en formato parrilla/ crea una matriz de gráficas
  
  
 GGAlly-visión general de un dataframe 
 
 Diagonal: función de distribución (variable con respecto a si misma)
 Matriz simétrica: puntos simétricos se complementan: scatterplot - correlación
  


ggpairs(df[,num_cols_repr], 
        aes(colour = factor, 
            alpha = 0.4),
        title = "Análisis multivariante de x",
        upper = list(continuous = "density"),
        lower = list(combo = "denstrip"))+
  theme(plot.title = element_text(hjust = 0.5))  





# Gráficos 3D
VER

 
# Exportar gráficos a varios formatos de salida

Antes de realizar el gráfico se llama a la función del formato:

png(file="multivariant.png", width = 3000, height = 3000, res = 72)
postscript(file="multivariant.ps")
pdf(file="multivariant.pdf")
 
Al terminar el gráfico:
  
dev.off()
