---
title: "09.2 - Grafos de twitter"
author: "Ccanadas"
date: "2022-10-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Análisis de tweets

library(twitteR)
library(igraph)
library(dplyr)

api_key <- ""
api_secret <- ""
access_token <- ""
access_token_secret <- ""

Conectar a twitter:
setup_twitter_oauth(api_key, api_secret, access_token, access_token_secret)

Descargar tweets/parámetros filters:
all_tweets <- searchTwitter("tag", n = 2000)

Pasar a dataframe la lista:
all_tweets <- twListToDF(all_tweets)

sample_tweets <- all_tweets[numero de filas que necesitamos, ] #jugar con pocos tweets y aplicar luego los algoritmos a todos

Dividir tweets para crear network de tweets y otra de retweets para el grafo
split_tweets <- split(sample_tweets, sample_tweets$isRetweet)

Mutamos los retwees para quedarnos con el usuario y el tweet
retweets <- mutate(split_tweets[['TRUE']], #mutate añade una columna a la lista con condición dada del emisor del tweet
                   sender = substr(text, 5, regexpr(":",text)-1)) #nos quedamos con los retweets eliminando los 4 primero parámetros y quedádnonos con los usuarios que han hecho el retweet. (empezar la posición 5 y termina donde hay dos puntos :)


Nos quedamos con el emisor y el retweeteador en un DF para generar las aristas

`edge_list <- as.data.frame(cbind(sender = tolower(retweets$sender), receiver = tolower(retweets$screenName)))`


edge_list <- count(edge_list, sender, receiver) #lista de aristas (asigna un emisor a un receptor)

Creamos el objeto graph y el plot:

tweets_graph <- graph_from_data_frame(d=edge_list, directed = T)
save(tweets_graph, file="path/name.Rdata")


plot(tweets_graph, 
     #layout=layout.fruchterman.reingold,
     vertex.color = "blue",
     vertex.size = degree(tweets_graph, mode = "in"),
     vertex.label = NA,
     edge.arrow.size = 0.5,
     edge.arrow.width = 0.5,
     edge.width = edge_attr(tweets_graph)$n,
     edge.color=hsv(h=.9, s=1, v=.7, alpha = 0.5),
     main="título")

## Layouts basados en fuerzas y repulsión

library(devtools)
devtools::install_github("analyxcompany/ForceAtlas2")
library(ForceAtlas2)

Prueba los graphs que mejor queden en los datos y lo imprime en pantalla y genera el layout para luego pintarlo con igraph.

force_layout <- layout.forceatlas2(tweets_graph,
                                   iterations = 200,
                                   plotstep = 20) 

plot(tweets_graph, 
     layout = force_layout,
     vertex.color = "blue",
     vertex.size = degree(tweets_graph, mode = "in"),
     vertex.label = NA,
     edge.arrow.size = 0.5,
     edge.arrow.width = 0.5,
     edge.width = edge_attr(tweets_graph)$n,
     edge.color=hsv(h=.9, s=1, v=.7, alpha = 0.5),
     main="título")




### Gephi

App de visualización de grafos a partir del Rdata y convertir a graph.ml

write.graph(tweets_graph,
            file="pathname.graphml",
            format= "graphml")
            
layout: Yigan Hu: repulsión

