---
title: "09 - socialnetworks"
author: "Ccanadas"
date: "2022-09-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# API MeetUp

-


# Grafos


### Matriz de adyacencias sparsed o lista de aristas para representar grafos.

library(Matrix)

Cargar un objeto Rdata de usuarios y crear una sparse matrix.

`group_membership=sparseMatrix(users$group_id, users$user_id, x=T)` (X=T asigna TRUE si existe objeto en columna)

Matriz de adyacencia: reprentar users vs users, el valor ij vendrá dado por el número de elementos o grupos en común.

`adjacency<-t(group_membership)%*%group_membership`

Usuarios: nodos, Grupos: aristas o al revés. // Pintamos la matriz de adyacencia en un grafo.

Matriz de aristas se puede extraer como resumen de la matriz de adyacencia:

head(summary(adjacency)): Matriz de aristas

user_edgelist<-as.data.frame(summary(adjacency))

Nos quedamos el triángulo superior por ser una matriz simétrica:

`user_edgelist.upper<-users_edgelist[users_edgelist$i<users_edgelist$j]`

save(user_edgelist.upper, file=""): guardar en fichero para trabajar


## Grafos

E=aristas
G=grado
V=vertice

### Preprocesado

library(igraph)

load(rdata.object)

Si el objeto es muy grande: creamos una red social reducida filtrando ocurrencias

users_edgelist.filtered <- users_edgelist.upper[users_edgelist.upper$x>15,]
nrow(users_edgelist.filtered)
head(users_edgelist.filtered)


reescalar los identificadores de usuario / truco para visualizar mejor

`uids <- unique(c(users_edgelist.filtered$i, users_edgelist.filtered$j))`

i <- match(users_edgelist.filtered$i, uids)
j <- match(users_edgelist.filtered$j, uids)

new.graph <- data.frame(i, j, x = users_edgelist.filtered$x)

### Representación

g <- graph.data.frame(new.graph, directed = F)
g #nomenclatura: vertice/arista
save(g, file = "path")
plot.igraph(g, vertex.size = 20) 

plot.igraph(g, layout = layout.circle, vertex.size = 20) ##layout es la distribución de los vértices

plot.igraph(g, edge.curved = T, vertex.color = "pink", edge.color = "blue")

`V(g)$size = degree(g)*4` -> el tamaño del nodo es igual al grado de importancia

plot.igraph(g, edge.curved = T, vertex.color = "pink", edge.color = "blue")

Darle color por importancia:
color <- ifelse(degree(g)>5,"red", "blue")
size <- degree(g)*4
plot.igraph(g, vertex.label = NA,
            layout = layout.fruchterman.reingold,
            vertex.color = color,
            vertex.size = size)
            
Grosor de las aristas propocional al peso:
E(g)$x 
plot.igraph(g, edge.curved =T, edge.color = "black", 
            edge.width = (E(g)-min(E(g))+1)/5)


## Más opciones

Antes de dibujar un grafo, hay que crear un objeto graph.data.frame a partir de un data.frame 

####Grafo dirigido

Hay que cargar el DF dirigido:
dg <- graph.data.frame(new.graph, directed=T)
save(dg, file = "../data/tema9/meetup-hiking-d-graph.Rdata")
plot.igraph(dg, edge.curved = T, edge.color = "black",
            vertex.label.cex = 0.5)

####Grafo con pesos en las aristas

Tercera columna: peso de arista con nombre "weight"

new.graph.w <- new.graph
names(new.graph.w) <- c("i","j","weight")
wg<-graph.data.frame(new.graph.w,directed=F)
wg
`E(wg)$weight`
`plot.igraph(wg, edge.label = E(wg)$weight)` ##acceso a los pesos de las aristas E(wg) y pintar labels



####Obtener la matriz de adyacencia de un grafo


get.adjacency(g, type = "both")
get.adjacency(g, type = "upper", attr = "x") ##con pesos


####Obtener la lista de aristas a partir de un grafo

 
get.data.frame(g)
V(g)$size = degree(g)
get.data.frame(g, "vertices")
get.data.frame(g, "both")


####Grafo bipartito

Grafo donde los nodos se dividen en dos grupos de modo que solamente están relacionados los de un grupo con los del otro.
No existen conexiones intergrupo.

g1 <- rbinom(10,1,0.5)
g2 <- rbinom(10,1,0.5)
g3 <- rbinom(10,1,0.5)
g4 <- rbinom(10,1,0.5)
g5 <- rbinom(10,1,0.5)

membership <- data.frame(g1,g2,g3,g4,g5)
names(membership)
rownames(membership) <- c("u1","u2","u3","u4","u5","u6","u7","u8","u9","u10")
rownames(membership)

bg <- graph.incidence(membership)
bg
V(bg)$type
V(bg)$name

layout <- layout.bipartite(bg) ##distribución de vértices
save(bg, file = "../data/tema9/bipartite-graph.Rdata")
plot(bg, layout=layout, vertex.size = 15)



####Proyección de un grafo bipartito

relaciones entre usuarios y grupos:


p <- bipartite.projection(bg)
p

plot(p$proj1, vertex.size = 15)
plot(p$proj2, vertex.size = 20)



# Métricas

Betweeness (Intermediación) y Closeness (Cercanía): alto grado de centralidad: influencers.

library(igraph)

Cargar ficheros de grafos: Rdata

#### Grados


degree(g): centralizar los vértices/calcula el grado

degree(g, "nodo o grupo") : específico /parámetro mode="in" o "out" te da el grado de salida o entrada

options(digits=3)
degree.distribution(g) : distribución de los grados en el grafo


#### Betweenness

betweenness(g) :el grado de intermediación de cada nodo

betweenness(g, "nodo")

edge.betweenness(g): importancia de la arista / edge.betweenness(g, "nodo")



#### Closeness

closeness(g)
closeness(g, mode="in" / "out") : cuando son dirigidos hay que especificar si in o out //all y total también



## Conexiones en grafos dirigidos

E(g): aristas

neighbors(g,vértice(usuarios, nodos, etc)): vecinos innmediatos

V(g) : vértices

Podemos quedarnos con los nombres con $name[neighbors(g, nodo)]


neighborhood(g, order=dist, nodes=nodo): encontrar el vecindario de un nodo de distancia (orden) X


Añadir nodos al objeto grafo:

new.g<-g+vertex(v+1, v+2,...)# v=vertices del nodo original

Añadir aristas:

new.g<-new.g+vertex(v+1,v+2) : añade una arista entre el nodo v+1 y v+2


Borrar vértices de grado=0 (o cualquiera que no nos interese con grado<n)

new.g<-delete.vertices(new.g, V(new.g)[degree(new.g)==0])

Cuidado: hay que nombrar los vértices asignando los valores, sino, podemos borrar el identificador y se reasignen los valores.


Subgrafo inducido: g.sub<-induced.subgraph(g, c(vertices que queremos))
























